rembish_org/models/flight.py
from sqlalchemy.dialects import mysql

from .drone import Drone
from .trip import Trip
from .world import Country
from ..libraries.database import db


class FlightLog(db.Model):
    __tablename__ = "drone_flight_log"

    id = db.Column(db.Integer, primary_key=True)
    private = db.Column(db.Boolean, default=False)

    drone_id = db.Column(db.SmallInteger, db.ForeignKey(Drone.id), nullable=False)
    drone = db.relationship(Drone)

    country_id = db.Column(db.SmallInteger, db.ForeignKey(Country.id))
    country = db.relationship(Country)

    trip_id = db.Column(db.Integer, db.ForeignKey(Trip.id), nullable=True)
    trip = db.relationship(Trip)

    date = db.Column(db.Date, nullable=False, server_default=db.text("(CURRENT_DATE)"))
    in_air = db.Column(db.Boolean, default=False)

    location = db.Column(db.String(length=200))
    latitude = db.Column(db.Numeric(10, 8), nullable=False)
    longitude = db.Column(db.Numeric(11, 8), nullable=False)
    place_id = db.Column(db.String(length=50))

    takeoffs = db.relationship(
        "Takeoff", lazy="select", backref=db.backref("flight", lazy="joined"), cascade="all, delete")

    type = db.Column(mysql.SET("photo", "video", "training"), default="photo")
    activity = db.Column(db.String(length=100))
    description = db.Column(db.String(length=200))

    @classmethod
    def get_flights_for(cls, user, private=False):
        result = []
        for flight in db.session.execute("""
            SELECT
                dfl.*,  c.code  AS `country_code`, c.name AS `country`,
                COALESCE(d.callsign, d.nickname, CONCAT(dv.name, '', dm.name)) AS `drone_name`,
                MIN(dt.start) AS `takeoff`,
                MAX(dt.finish) AS `landing`,
                MAX(dt.altitude) AS `altitude`,
                SUM(dt.distance) AS `distance`,
                SEC_TO_TIME(SUM(TIME_TO_SEC(TIMEDIFF(dt.finish, dt.start)))) AS `duration`,
                COUNT(dt.flight_id) AS `landing_count`
            FROM drone_flight_log AS dfl
            JOIN drone_takeoffs AS dt ON dt.flight_id = dfl.id
            JOIN drones AS d ON d.id = dfl.drone_id
            JOIN drone_models AS dm ON dm.id = d.model_id
            JOIN drone_vendors AS dv ON dv.id = dm.vendor_id
            JOIN countries AS c ON c.id = dfl.country_id
            WHERE
                d.owner_id = :owner_id AND dfl.private IN (0, :private)
            GROUP BY dt.flight_id
            ORDER BY dfl.date DESC, dt.start DESC
        """, {"owner_id": user.id, "private": int(private)}):
            row = dict(flight)
            row["type"] = row["type"].split(",") if row["type"] else []
            result.append(row)

        return result

    @classmethod
    def get_statistics_for(cls, user):
        response = db.session.execute("""
            SELECT
                COUNT(DISTINCT dfl.id) AS `flight_count`,
                COUNT(DISTINCT dt.id) AS `takeoff_count`,
                COUNT(DISTINCT dfl.place_id) AS `place_count`,
                COUNT(DISTINCT dfl.country_id) AS `country_count`,
                COUNT(DISTINCT d.id) AS `drone_count`,
                SUM(dt.distance) AS `distance`,
                MAX(dt.altitude) AS `altitude`,
                SEC_TO_TIME(SUM(TIME_TO_SEC(TIMEDIFF(dt.finish, dt.start)))) AS `duration`,
                DATEDIFF(MAX(dfl.date), MIN(dfl.date)) AS `days`
            FROM drone_flight_log AS dfl
            JOIN drone_takeoffs AS dt ON dt.flight_id = dfl.id
            JOIN drones AS d ON d.id = dfl.drone_id
            WHERE d.owner_id = :owner_id
        """, {"owner_id": user.id})
        for row in response:
            return row


class Takeoff(db.Model):
    __tablename__ = "drone_takeoffs"

    id = db.Column(db.Integer, primary_key=True)

    flight_id = db.Column(db.Integer, db.ForeignKey(FlightLog.id), nullable=False)

    start = db.Column(db.Time, nullable=False, server_default=db.text("(CURRENT_DATE)"))
    finish = db.Column(db.Time)
    distance = db.Column(db.Integer)
    altitude = db.Column(db.Integer)

rembish_org/forms/flight.py
from datetime import date

from flask_wtf import FlaskForm
from wtforms import DateField, StringField, TextAreaField, Form, TimeField, FieldList, \
    FormField, SubmitField, SelectMultipleField, HiddenField, BooleanField, IntegerField, DecimalField
from wtforms.validators import DataRequired, Optional
from wtforms.widgets import HiddenInput

from ..libraries.forms import LazySelectField
from ..libraries.globals import my_drones


class TakeoffForm(Form):
    start = TimeField(label="Take-off", format="%H:%M:%S", validators=[DataRequired()])
    finish = TimeField(label="Landing", format="%H:%M:%S", validators=[Optional(strip_whitespace=True)])
    distance = IntegerField(label="Distance", validators=[Optional(strip_whitespace=True)])
    altitude = IntegerField(label="Altitude", validators=[Optional(strip_whitespace=True)])


class FlightForm(FlaskForm):
    date = DateField(label="Date", default=date.today(), format="%d.%m.%Y")
    drone_id = LazySelectField(
        label="Drone",
        choices=lambda: [(drone.id, drone) for drone in my_drones], default=lambda: my_drones[0].id,
        validators=[DataRequired()])
    location = StringField(label="Location")
    place_id = HiddenField(validators=[Optional(strip_whitespace=True)])
    latitude = DecimalField(widget=HiddenInput(), validators=[DataRequired()])
    longitude = DecimalField(widget=HiddenInput(), validators=[DataRequired()])
    type = SelectMultipleField(label="Type", choices=[
        ('photo', 'Photo'), ('video', 'Video'), ('training', 'Training'),
    ], default=['photo'])
    activity = StringField(label="Activity", validators=[Optional(strip_whitespace=True)])
    description = TextAreaField(label="Additional information", validators=[Optional(strip_whitespace=True)])
    takeoffs = FieldList(FormField(TakeoffForm), min_entries=1)
    private = BooleanField(label="Is private?", default=False)
    register = SubmitField(label="Register")

rembish_org/blueprints/drones.py
from flask import Blueprint

from ..libraries.templating import with_template
from ..models.drone import Drone

root = Blueprint("drones", __name__)


@root.route("/drones")
@with_template
def list_():
    pass


@root.route("/drones/<int:drone_id>")
@with_template
def show(drone_id):
    drone = Drone.query.get_or_404(drone_id)
    return {
        "drone": drone,
    }

rembish_org/blueprints/flights.py
from flask import Blueprint, redirect, url_for
from flask_login import current_user, login_required

from ..forms.flight import FlightForm
from ..libraries.database import db
from ..libraries.geonames import geonames
from ..libraries.globals import me
from ..libraries.templating import with_template, with_json
from ..models.flight import FlightLog, Takeoff
from ..models.world import Country

root = Blueprint("flights", __name__)


@root.route("/flights")
@with_template
def map_():
    stats = FlightLog.get_statistics_for(me)
    return {
        "stats": stats,
    }


@root.route("/flights/log")
@with_template
def log():
    flights = FlightLog.get_flights_for(me, private=current_user == me)

    return {
        "flights": flights,
    }


@root.route("/flights/<int:flight_id>")
@with_template
def show(flight_id):
    flight = FlightLog.query.get_or_404(flight_id)
    return {
        "flight": flight,
    }


@root.route("/flights/new", methods=("GET", "POST"))
@login_required
@with_template
def new():
    form = FlightForm()
    if form.validate_on_submit():
        flight = FlightLog()
        for _ in form.takeoffs:
            flight.takeoffs.append(Takeoff())
        form.populate_obj(flight)

        code = geonames.get_code_by(flight.latitude, flight.longitude)
        if code:
            country = Country.get_by(code)
            flight.country = country

        db.session.add(flight)
        db.session.commit()

        return redirect(url_for("flights.log"))

    return {
        "form": form,
    }


@root.route("/flights/takeoff", methods=("POST",))
@with_json
def takeoff():
    pass


@root.route("/flights/places")
@with_json
def places():
    flights = FlightLog.get_flights_for(me, private=current_user == me)
    spots = []
    for flight in flights:
        spot = {
            "location": flight["location"],
            "latitude": float(flight["latitude"]),
            "longitude": float(flight["longitude"]),
            "drone_id": flight["drone_id"],
        }
        spots.append(spot)
    return {
        "places": spots,
    }

rembish_org/templates/flights/log.html
{% extends "layout.html" %}

{% block title %}Flight log - Alex Rembish{% endblock %}

{% block css %}
    <link href="{{ static_url('vendor/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
{% endblock %}

{% block main %}
    <section class="flightlog">
        <div class="container">
            <div class="section-title">
                <h2>Drone flight log</h2>
            </div>

            {% if current_user.has_role("administrator") %}
                <p class="text-right"><a href="{{ url_for("flights.new") }}" class="btn btn-primary btn-lg" role="button">Register flight</a></p>
            {% endif %}

            <div class="table-responsive"><table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="align-text-top">#</th>
                        <th scope="col">Date<br><small>Take-off &ndash; Landing</small></th>
                        <th scope="col">Place<br><small>Additional information</small></th>
                        <th scope="col" class="align-text-top">Drone<br><small>Distance</small></th>
                        <th scope="col" class="align-text-top">Duration</th>
                        <th scope="col">Type<br><small>Activity</small></th>
                    </tr>
                </thead>
                <tbody>
                {% for flight in flights %}
                    <tr {% if flight.private %}class="table-secondary"{% endif %}>
                        <th scope="row">{{ loop.index }}</th>
                        <td class="text-nowrap">
                            {{ flight.date.strftime("%d.%m.%Y") }}<br>
                            <small>{{ flight.takeoff }} &ndash; {{ flight.landing }}</small>
                        </td>
                        <td>
                            {% if flight.country_code %}
                                <span class="flag-icon flag-icon-{{ flight.country_code | lower }}" title="{{ flight.country }}"></span>
                            {% endif %}
                            <a href="{{ url_for("flights.show", flight_id=flight.id) }}">{{ flight.location | default("Untitled") }}</a>
                            {% if flight.description %}<br><small>{{ flight.description }}</small>{% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for("drones.show", drone_id=flight.drone_id) }}">{{ flight.drone_name }}</a>
                            {% if flight.distance %}<br><small>{{ flight.distance }} m</small>{% endif %}
                        </td>
                        <td>
                            {{ flight.duration }}
                            {% if flight.landing_count > 1 %}<br><small>{{ flight.landing_count }} take-offs</small>{% endif %}
                        </td>
                        <td class="text-nowrap">
                            {{ flight.type | join(" / ") | title }}
                            {% if flight.activity %}<br><small>{{ flight.activity }}</small>{% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table></div>
        </div>
    </section>
{% endblock %}

rembish_org/templates/flights/map.html
{% extends "layout.html" %}

{% block title %}Drone statistics - Alex Rembish{% endblock %}

{% block js %}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config['GOOGLE_API_KEY'] }}&libraries=places&language=en&callback=initMap"></script>
    <script>
    function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
            center: {lat: 50.08804, lng: 14.42076},  // Default position is Prague
            zoom: 13,
            mapTypeId: "roadmap",
        });

        const icons = [
            {}, // No drones with ID = 0
            {
                path: google.maps.SymbolPath.CIRCLE,
                fillColor: '#0563bb',
                fillOpacity: 0.6,
                strokeColor: '#00A',
                strokeOpacity: 0.9,
                strokeWeight: 1,
                scale: 4
            },
            {
                path: google.maps.SymbolPath.CIRCLE,
                fillColor: '#05bb63',
                fillOpacity: 0.6,
                strokeColor: '#0A0',
                strokeOpacity: 0.9,
                strokeWeight: 1,
                scale: 4
            }
        ]

        $.ajax("{{ url_for('flights.places') }}").done(function (data, textStatus, jqXHR) {
            const bounds = new google.maps.LatLngBounds();

            for (let i in data["places"]) {
                const place = data["places"][i];
                const position = new google.maps.LatLng(place.latitude, place.longitude);
                const marker = new google.maps.Marker({
                    map,
                    title: place.location,
                    position: position,
                    icon: icons[place.drone_id]
                });
                bounds.extend(position);
            }

            map.fitBounds(bounds);
        });
    }
    </script>
{% endblock %}

{% block main %}
    <section class="flightlog">
        <div class="container">
            <div class="section-title">
                <h2>Drone statistics</h2>
            </div>

            <div class="row">
                <div class="col-4">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{{ url_for("flights.log") }}">Total flights</a> <span class="badge badge-primary badge-pill">{{ stats.flight_count }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Total take-offs <span class="badge badge-primary badge-pill">{{ stats.takeoff_count }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Total places <span class="badge badge-primary badge-pill">{{ stats.place_count }}</span>
                        </li>
                    </ul>
                </div>
                <div class="col-4">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Total distance <span class="badge badge-primary badge-pill">{{ "{:,.0f}".format(stats.distance / 1000) }} km</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Total flight time <span class="badge badge-primary badge-pill">{{ stats.duration }}</span>
                        </li>
                        {% if current_user.has_role("administrator") %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Max altitude <span class="badge badge-primary badge-pill">{{ stats.altitude }} m</span>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-4">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{{ url_for("drones.list_") }}">Drones owned</a> <span class="badge badge-primary badge-pill">{{ stats.drone_count }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Pilot experience <span class="badge badge-primary badge-pill">{{ stats.days }} days</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Countries visited <span class="badge badge-primary badge-pill">{{ stats.country_count }}</span>
                        </li>
                    </ul>
                </div>
            </div>

            <div id="map" style="height: 550px; margin-bottom: 10px;"></div>
        </div>
    </section>
{% endblock %}

rembish_org/templates/flights/new.html
{% extends "layout.html" %}

{% block title %}New flight - Alex Rembish{% endblock %}

{% block css %}
  <link href="{{ static_url('vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}" rel="stylesheet">
{% endblock %}

{% block js %}
  <script src="{{ static_url('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
  <script src="{{ static_url('vendor/bootstrap-select/js/bootstrap-select.min.js') }}"></script>
  <script src="{{ static_url('vendor/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
  <script src="{{ static_url('vendor/moment/moment.min.js') }}"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config['GOOGLE_API_KEY'] }}&libraries=places&language=en&callback=initMap"></script>

    <script>
    function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
            center: {lat: 50.08804, lng: 14.42076},  // Default position is Prague
            zoom: 13,
            mapTypeId: "roadmap",
        });
        const locationInput = document.getElementById("location");
        const searchBox = new google.maps.places.SearchBox(locationInput);
        const gps = $("#gps"), lat = $("#latitude"), lng = $("#longitude");

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition((position => {
                const latitude  = position.coords.latitude;
                const longitude = position.coords.longitude;
                map.setCenter(new google.maps.LatLng(latitude, longitude));
            }));
        }

        let markerLocation, markerPosition;

        map.addListener("bounds_changed", () => {
            searchBox.setBounds(map.getBounds());
        });

        map.addListener("dblclick", (event) => {
            if (markerPosition) {
                markerPosition.setMap(null);
            }

            const position = event.latLng;
            markerPosition = new google.maps.Marker({
                map,
                title: "Exact position",
                position: position
            });

            gps.val(position.lat() + ", " + position.lng());
            lat.val(position.lat());
            lng.val(position.lng());
        });

        searchBox.addListener("places_changed", () => {
            const place_id = $("#place_id");
            place_id.val("");

            const places = searchBox.getPlaces();
            if (places.length === 0 || !places[0].geometry) {
                return;
            }

            if (markerLocation) {
                markerLocation.setMap(null);
            }
            if (markerPosition) {
                markerPosition.setMap(null);
            }

            const place = places[0];
            const bounds = new google.maps.LatLngBounds();
            const icon = {
                url: place.icon,
                size: new google.maps.Size(71, 71),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(17, 34),
                scaledSize: new google.maps.Size(25, 25),
            };
            const placeLocation = place.geometry.location;

            markerLocation = new google.maps.Marker({
              map, icon,
              title: place.name,
              position: placeLocation,
            });
            place_id.val(place.place_id);

            gps.val(placeLocation.lat() + ", " + placeLocation.lng());
            lat.val(placeLocation.lat());
            lng.val(placeLocation.lng());

            if (place.geometry.viewport) {
                bounds.union(place.geometry.viewport);
            } else {
                bounds.extend(place.geometry.location);
            }

            map.fitBounds(bounds)
        });
    }

    let takeoffs = 0;
    $(document).ready(() => {
        $.fn.datepicker.defaults.autoclose = true;

        $.fn.timepicker.defaults.secondStep = 1;
        $.fn.timepicker.defaults.minuteStep = 1;
        $.fn.timepicker.defaults.icons = {
            up: "icofont icofont-rounded-up",
            down: "icofont icofont-rounded-down"
        };
        $.fn.timepicker.defaults.showMeridian = false;
        $.fn.timepicker.defaults.showSeconds = true;

        $(".takeoff-delete").click(function() {
            $(this).closest(".form-row").remove();
            return false;
        });
        $("#takeoff-add").click(() => {
            takeoffs++;
            let div = $("#takeoffs>div:first").clone(true, true);
            $("input", div).each((i, element) => {
                $(element).prop("id", $(element).prop("id").replace("--", "-" + takeoffs + "-"));
                $(element).prop("name", $(element).prop("id"));
            });
            div.removeClass("d-none");
            $(div).insertAfter("#takeoffs>div:last");
            return false;
        });

        $("input.tp").change(function() {
            const self = $(this);
            const row = self.closest(".form-row");

            let start = $(".tp-start", row).val();
            let duration = $(".tp-duration", row).val();
            let finish = $(".tp-finish", row).val();

            if (start && finish && self.hasClass("tp-finish")) {
                start = moment(start, "HH:mm:ss");
                finish = moment(finish, "HH:mm:ss");
                duration = moment.utc(finish.diff(start, "milliseconds"));

                $(".tp-duration", row).val(duration.format("HH:mm:ss"));
            } else if (start && duration) {
                start = moment(start, "HH:mm:ss");
                duration = moment.duration(duration);
                finish = start.add(duration, "seconds");

                $(".tp-finish", row).val(finish.format("HH:mm:ss"));
            }
        });
    });
    </script>
{% endblock %}

{% block main %}
    <section>
        <div class="container">
            <div class="section-title">
                <h2>Flight registration</h2>
            </div>

            <form method="post" action="{{ url_for('flights.new') }}">
                {{ form.csrf_token }}
                <div class="form-row">
                    <div class="form-group col-2">
                        <div class="input-group date" data-provide="datepicker" data-date-format="dd.mm.yyyy" data-date-week-start="1">
                            {{ form.date(class_="form-control") }}
                            <div class="input-group-append">
                                <div class="input-group-text"><span class="icofont icofont-calendar"></span></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-4">{{ form.drone_id(class_="form-control selectpicker") }}</div>
                    <div class="form-group col-3">{{ form.type(class_="form-control selectpicker") }}</div>
                </div>

                <div class="form-row">
                    <div class="form-group col">{{ form.location(class_="form-control", placeholder=form.location.label.text) }} {{ form.place_id }}</div>
                    <div class="form-group col-5">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><span class="icofont icofont-air-balloon"></span></div>
                            </div>
                            <input type="text" class="form-control" id="gps" required>{{ form.latitude }}{{ form.longitude }}
                        </div>
                    </div>
                </div>

                <div id="map" style="height: 300px; margin-bottom: 10px;"></div>

                <div class="form-row">
                    <div class="form-group col-2">Take-off</div>
                    <div class="form-group col-2">Duration</div>
                    <div class="form-group col-2">Landing</div>
                    <div class="form-group col-2">Distance, m</div>
                    <div class="form-group col-2">Altitude, m</div>
                    <div class="form-group col-1"><button class="btn btn-outline-dark" id="takeoff-add"><span class="icofont icofont-plus"></span></button></div>
                </div>
                <div id="takeoffs">
                    <div class="form-row d-none">
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input class="form-control tp tp-start" data-provide="timepicker" id="takeoffs--start" type="text" value="">
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input class="form-control tp tp-duration" data-default-time="false" data-max-hours="2" data-provide="timepicker" id="takeoffs--duration" type="text" value="">
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input id="takeoffs--finish" type="text" class="form-control tp tp-finish" data-provide="timepicker">
                            </div>
                        </div>
                        <div class="form-group col-2"><input class="form-control" id="takeoffs--distance" type="number" value="" min="0"></div>
                        <div class="form-group col-2"><input class="form-control" id="takeoffs--altitude" type="number" value=""></div>
                        <div class="form-group col-1"><button class="btn btn-outline-danger takeoff-delete"><span class="icofont icofont-trash"></span></button></div>
                    </div>
                {% for takeoff in form.takeoffs %}
                    <div class="form-row">
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                {{ takeoff.start(class_="form-control tp tp-start", data_provide="timepicker") }}
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input class="form-control tp tp-duration" data-default-time="false" data-max-hours="2" data-provide="timepicker" id="takeoffs-{{ loop.index0 }}-duration" name="takeoffs-{{ loop.index0 }}-duration" type="text" value="">
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                {{ takeoff.finish(class_="form-control tp tp-finish", data_provide="timepicker") }}
                            </div>
                        </div>
                        <div class="form-group col-2">{{ takeoff.distance(class_="form-control", min=0) }}</div>
                        <div class="form-group col-2">{{ takeoff.altitude(class_="form-control") }}</div>
                        <div class="form-group col-1"><button class="btn btn-outline-danger takeoff-delete"><span class="icofont icofont-trash"></span></button></div>
                    </div>
                {% endfor %}
                </div>

                <div class="form-row"><div class="form-group col">{{ form.activity(class_="form-control", placeholder=form.activity.label.text) }}</div></div>
                <div class="form-row"><div class="form-group col">{{ form.description(class_="form-control", placeholder=form.description.label.text) }}</div></div>
                <div class="form-group"><div class="form-check">{{ form.private(class_="form-check-input") }} {{ form.private.label(class_="form-check-label") }}</div></div>

                {{ form.register(class_="form-control") }}
            </form>
        </div>
    </section>
{% endblock %}

rembish_org/templates/flights/show.html
{% extends "layout.html" %}