rembish_org/blueprints/index.py
from flask import Blueprint, request, render_template
from flask_dance.contrib.google import google
from flask_login import current_user
from markdown2 import markdown_path
from oauthlib.oauth2 import InvalidClientIdError
from pkg_resources import resource_filename

from ..forms.contact import ContactForm
from ..libraries.telegram import telegram, TelegramError
from ..libraries.templating import with_template, with_json

root = Blueprint('index', __name__)


@root.route("/")
@with_template
def index():
    pass


@root.route("/cv")
@with_template
def cv():
    pass


@root.route("/changelog")
@with_template
def changelog():
    filename = resource_filename("rembish_org", "templates/CHANGELOG.md")
    md = markdown_path(filename)
    return {
        "changelog": md,
    }


@root.route("/contact")
@with_template
def contact():
    info = {}
    if current_user and google.authorized:
        try:
            response = google.get("/oauth2/v1/userinfo")
            if response.ok:
                info = response.json()
        except InvalidClientIdError:
            pass

    form = ContactForm(data=info)
    return {
        "form": form,
    }


@root.route("/contact/message", methods=("POST",))
@with_json
def message():
    form = ContactForm(request.form)
    if not form.validate_on_submit():
        return {
            "status": 403,
            "errors": form.errors,
        }

    text = render_template("messages/contact.md", **form.data)

    try:
        telegram.send(text, parse_mode="Markdown")
    except TelegramError as tge:
        return {
            "status": tge.code,
            "message": tge.message,
        }

    return {}

rembish_org/blueprints/trips.py
from flask import Blueprint, request, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.datastructures import MultiDict

from ..forms.trip import TripForm
from ..libraries.database import db
from ..libraries.templating import with_template
from ..models.trip import Trip, TripCompanion, TripSettlement
from ..models.user import User
from ..models.world import Settlement

root = Blueprint("trips", __name__)


@root.route("/trips")
@with_template
def map_():
    return {}


@root.route("/trips/list")
@with_template
def index():
    return {}


@root.route("/trips/add", methods=("GET", "POST"))
@login_required
@with_template
def add():
    data = None

    if request.method == "POST":
        companions = request.form.getlist("companion_ids").copy()
        data = MultiDict()
        i = 0
        for key, value in request.form.items(multi=True):
            if key.startswith("companions-"):
                user_id = key.lstrip("companions-")
                data[f"companions-{i}-user_id"] = user_id
                data[f"companions-{i}-full"] = value
                i += 1
                companions.remove(user_id)
            else:
                data.add(key, value)

        for user_id in companions:
            data[f"companions-{i}-user_id"] = user_id
            i += 1

    form = TripForm(formdata=data)
    if form.validate_on_submit():
        with db.session.no_autoflush:
            trip = Trip(traveler=current_user)
            for row in form.companions:
                tc = TripCompanion(companion=User.get_by(row.data["user_id"]))
                trip.companions.append(tc)
            for row in form.settlements:
                ts = TripSettlement(settlement=Settlement.get_or_create(**row.data["json"]))
                trip.settlements.append(ts)
            form.populate_obj(trip)
            db.session.add(trip)

        db.session.commit()
        return redirect(url_for("trips.index"))

    print(form.errors)

    return {
        "form": form,
    }

rembish_org/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="{# TODO #}" name="description">
  <meta content="{# TODO #}" name="keywords">

  <!-- Favicons -->
  <link href="{{ static_url('imgs/favicon.ico') }}" rel="icon">
  <link href="{{ static_url('imgs/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ static_url('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/icofont/icofont.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/flaticon/flaticon.css') }}" rel="stylesheet">
  {% block css %}{% endblock %}

  <!-- Template Main CSS File -->
  <link href="{{ static_url('css/style.css') }}" rel="stylesheet">
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <button type="button" class="mobile-nav-toggle d-xl-none"><i class="icofont icofont-navigation-menu"></i></button>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex flex-column justify-content-center">

    <nav class="nav-menu">
      <ul>
        <li{{ ' class="active"' | safe if request.endpoint == "index.index" }}><a href="{{ url_for('index.index') }}"><i class="bx bx-home"></i> <span>Home</span></a></li>
        <li{{ ' class="active"' | safe if ".cv" in request.endpoint }}><a href="{{ url_for('index.cv') }}"><i class="bx bx-file-blank"></i> <span>Curriculum Vitae</span></a></li>
        <li{{ ' class="active"' | safe if ".contact" in request.endpoint }}><a href="{{ url_for('index.contact') }}"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>
        <li{{ ' class="active"' | safe if "trips." in request.endpoint }}><a href="{{ url_for('trips.map_') }}"><i class="bx bx-world"></i> <span>Trips</span></a></li>
        <li{{ ' class="active"' | safe if "flights." in request.endpoint }}><a href="{{ url_for('flights.map_') }}"><b class="flaticon-drone-14"></b> <span>Drone flights</span></a></li>
      </ul>
      <ul class="nav-menu">
        {% if current_user %}
        <li><a href="{{ url_for('google.logout') }}"><i class="bx bx-log-out-circle"></i> <span>Logout</span></a></li>
        {% else %}
        <li><a href="{{ url_for('google.login') }}"><i class="bx bx-log-in-circle"></i> <span>Login</span></a></li>
        {% endif %}
      </ul>
    </nav><!-- .nav-menu -->

  </header><!-- End Header -->

  <main id="main">{% block main %}
  {% endblock %}</main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="copyright">
          Content copyright &copy; <strong>Alex Rembish</strong> 2013&ndash;{{ now.year }}
      </div>
      <div class="credits">
        Python code is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a><br>
        CSS and HTML are based on a paid version of <a href="https://bootstrapmade.com/free-html-bootstrap-template-my-resume/">MyResume</a> by <a href="https://bootstrapmade.com/">BootstrapMade</a><br>
        Drone icons are from <a href="https://www.flaticon.com">flaticon.com</a>. Under <a href="https://creativecommons.org/licenses/by/3.0/">CC</a>: <a data-file="drone-19" href="https://www.freepik.com">Freepik</a><br>
        Source code (<a href="{{ url_for('index.changelog') }}">version {{ version }}</a>) can be found on <a href="https://gitlab.com/rembish/rembish_org">GitHub</a>
        <!--
         Based on MyResume - v2.1.0 (https://bootstrapmade.com/free-html-bootstrap-template-my-resume/).
         Template was properly purchased (Order #18932898)
         -->
      </div>
    </div>
  </footer><!-- End Footer -->

  <!-- Vendor JS Files -->
  <script src="{{ static_url('vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ static_url('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  {% block js %}{% endblock %}

  <!-- Template Main JS File -->
  <script src="{{ static_url('js/main.js') }}"></script>

</body>

</html>