rembish_org/forms/contact.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, EmailField
from wtforms.validators import DataRequired, Length


class ContactForm(FlaskForm):
    name = StringField(label="Your name", validators=[DataRequired(), Length(min=4)])
    email = EmailField(label="Your email", validators=[DataRequired()])
    subject = StringField(label="Subject")
    message = TextAreaField(label="Message", validators=[DataRequired()])

    submit = SubmitField(label="Send message")

rembish_org/blueprints/index.py
from flask import Blueprint, request, render_template
from flask_dance.contrib.google import google
from flask_login import current_user
from markdown2 import markdown_path
from oauthlib.oauth2 import InvalidClientIdError
from pkg_resources import resource_filename

from ..forms.contact import ContactForm
from ..libraries.telegram import telegram, TelegramError
from ..libraries.templating import with_template, with_json

root = Blueprint('index', __name__)


@root.route("/")
@with_template
def index():
    pass


@root.route("/cv")
@with_template
def cv():
    pass


@root.route("/changelog")
@with_template
def changelog():
    filename = resource_filename("rembish_org", "templates/CHANGELOG.md")
    md = markdown_path(filename)
    return {
        "changelog": md,
    }


@root.route("/contact")
@with_template
def contact():
    info = {}
    if current_user and google.authorized:
        try:
            response = google.get("/oauth2/v1/userinfo")
            if response.ok:
                info = response.json()
        except InvalidClientIdError:
            pass

    form = ContactForm(data=info)
    return {
        "form": form,
    }


@root.route("/contact/message", methods=("POST",))
@with_json
def message():
    form = ContactForm(request.form)
    if not form.validate_on_submit():
        return {
            "status": 403,
            "errors": form.errors,
        }

    text = render_template("messages/contact.md", **form.data)

    try:
        telegram.send(text, parse_mode="Markdown")
    except TelegramError as tge:
        return {
            "status": tge.code,
            "message": tge.message,
        }

    return {}

rembish_org/templates/index/changelog.html
{% extends "layout.html" %}
{% block title %}Changelog | Alex Rembish{% endblock %}

{% block main %}
    <section id="changelog" class="changelog">
        <div class="container">
            {{ changelog | safe }}
        </div>
    </section>
{% endblock %}

rembish_org/templates/index/contact.html
{% extends "layout.html" %}

{% block title %}Contact | Alex Rembish{% endblock %}

{% block js %}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config['GOOGLE_API_KEY'] }}&libraries=places&language=en&callback=initMap"></script>
    <script>
    let map;
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: {lat: 50.08804, lng: 14.42076},  // Default position is Prague
            zoom: 13,
            mapTypeId: "roadmap",
        });
        codeAddress($("#address").text());
    }

    function codeAddress(address) {
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({
            'address': address
        }, function(results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
                const location = results[0].geometry.location;
                const marker = new google.maps.Marker({
                    map: map,
                    position: location
                });

                const bounds = new google.maps.LatLngBounds();
                bounds.extend(location);
                map.fitBounds(bounds);
                map.setZoom(15);
            }
        });
    }
    </script>
{% endblock %}

{% block main %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <div class="container">
            <div class="section-title">
                <h2>Contact</h2>
            </div>

            <div id="map" style="height: 300px"></div>

            <div class="row mt-1">
                <div class="col-lg-4">
                    <div class="info">
                        <div class="address">
                            <i class="icofont icofont-google-map"></i>
                            <h4>Location: <a class="icofont icofont-briefcase badge badge-light float-right" href="{{ static_url('files/alex-rembish.vcf') }}"> vCard</a></h4>
                            <p id="address">Wichterlova 2372, 182 00 Praha 8-Libeň, Czech Republic</p>
                        </div>

                        <div class="email">
                            <i class="icofont icofont-envelope"></i>
                            <h4>Email: <a class="icofont icofont-lock badge badge-light float-right" href="{{ static_url('files/alex-rembish.asc') }}"> PGP</a></h4>
                            <p><a href="mailto:{{ config.ME_EMAIL }}">{{ config.ME_EMAIL }}</a></p>
                        </div>

                        <div class="phone">
                            <i class="icofont icofont-phone"></i>
                            <h4>
                                Call: <span class="float-right">
                                    <a class="badge badge-light" href="https://t.me/rembish" title="Telegram"><b class="bx bxl-telegram"></b></a>
                                    <a class="badge badge-light" href="https://wa.me/420775054554" title="WhatsApp"><b class="bx bxl-whatsapp"></b></a>
                                </span>
                            </h4>
                            <p><a href="tel:00420775054554">+420 775 054 554</a></p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 mt-5 mt-lg-0">
                    <form action="{{ url_for('index.message') }}" method="post" id="contact-form" class="email-form">
                        {{ form.csrf_token }}
                        <div class="form-row">
                            <div class="col-md-6 form-group">
                                {{ form.name(class_="form-control", placeholder=form.name.label.text) }}
                                <div class="validate"></div>
                            </div>
                            <div class="col-md-6 form-group">
                                {{ form.email(class_="form-control", placeholder=form.email.label.text) }}
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.subject(class_="form-control", placeholder=form.subject.label.text) }}
                            <div class="validate"></div>
                        </div>
                        <div class="form-group">
                            {{ form.message(class_="form-control", placeholder=form.message.label.text, rows=5) }}
                            <div class="validate"></div>
                        </div>
                        <div class="mb-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                        </div>
                        <div class="text-center">
                            {{ form.submit }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section><!-- End Contact Section -->
{% endblock %}

rembish_org/templates/index/index.html
{% extends "layout.html" %}

{% block title %}Hello, I'm Alex Rembish{% endblock %}

{% block main %}
    <section id="hero" class="d-flex flex-column justify-content-center">
        <div class="container">
            <h1>Alex Rembish</h1>
            <p>I'm <span class="typed" data-typed-items="a Senior Team Leader, a Python professional, an IT Manager, a Traveller, an Aerial Photographer, a Drone Pilot"></span></p>
            <div class="social-links">
                <a href="https://linkedin.com/in/rembish/" class="linkedin"><i class="bx bxl-linkedin-square"></i></a>
                <a href="https://github.com/rembish" class="github"><i class="bx bxl-github"></i></a>
                <a href="https://gitlab.com/rembish" class="gitlab"><i class="bx bxl-gitlab"></i></a>
                <a href="https://instagram.com/arembish/" class="instagram"><i class="bx bxl-instagram-alt"></i></a>
                <a href="https://twitter.com/rembish" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="https://facebook.com/rembish/" class="facebook"><i class="bx bxl-facebook-square"></i></a>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script src="{{ static_url('vendor/typed.js/typed.min.js') }}"></script>
{% endblock %}