rembish_org/models/trip.py
from sqlalchemy.dialects import mysql

from .user import User
from .world import Settlement
from ..libraries.database import db


class TripCompanion(db.Model):
    __tablename__ = "trip_companions"

    trip_id = db.Column(db.Integer, db.ForeignKey("trips.id"), primary_key=True)
    companion_id = db.Column(db.SmallInteger, db.ForeignKey(User.id), primary_key=True)
    partial = db.Column(db.Boolean, default=False)

    companion = db.relationship(User)


class TripSettlement(db.Model):
    __tablename__ = "trip_settlements"

    trip_id = db.Column(db.Integer, db.ForeignKey("trips.id"), primary_key=True)
    settlement_id = db.Column(db.Integer, db.ForeignKey(Settlement.id), primary_key=True)

    date = db.Column(db.Date, nullable=True)
    slightly = db.Column(db.Boolean, default=False)

    settlement = db.relationship(Settlement)


class Trip(db.Model):
    __tablename__ = "trips"

    id = db.Column(db.Integer, primary_key=True)
    traveler_id = db.Column(db.SmallInteger, db.ForeignKey(User.id), nullable=False)
    traveler = db.relationship(User)

    start_date = db.Column(db.Date, nullable=False, unique=True)
    finish_date = db.Column(db.Date, nullable=True)

    type = db.Column(mysql.SET("tourism", "business", "education", "moving", "other"), default="tourism")
    description = db.Column(db.Text, nullable=True)

    companions = db.relationship(TripCompanion)
    settlements = db.relationship(TripSettlement)

rembish_org/forms/trip.py
from functools import cached_property

from flask_wtf import FlaskForm
from wtforms import DateField, SelectMultipleField, Form, StringField, BooleanField, FieldList, FormField, \
    SubmitField, TextAreaField, IntegerField
from wtforms.validators import Optional, DataRequired
from wtforms.widgets import HiddenInput

from ..libraries.forms import LazySelectMultipleField, JSONField
from ..libraries.globals import me
from ..models.user import User


class CompanionForm(Form):
    user_id = IntegerField(widget=HiddenInput())
    full = BooleanField(default=False)

    @cached_property
    def user(self):
        return User.query.get(self.user_id.data)


class SettlementForm(Form):
    date = DateField(label="Day", format="%d.%m.%Y", validators=[Optional()])
    location = StringField(label="Location")
    json = JSONField(validators=[DataRequired()], widget=HiddenInput())
    slightly = BooleanField(default=False)


class TripForm(FlaskForm):
    start_date = DateField(label="From", format="%d.%m.%Y", validators=[DataRequired()])
    finish_date = DateField(label="To", format="%d.%m.%Y", validators=[Optional()])
    type = SelectMultipleField(label="Type", choices=[
        ('tourism', 'Tourism'), ('business', 'Business'), ('education', 'Education'),
        ('moving', 'Moving'), ('other', 'Other'),
    ], default=['tourism'], validators=[DataRequired()])
    companion_ids = LazySelectMultipleField(
        label="Companions", coerce=int,
        choices=lambda: [(user.id, user.fullname) for user in User.get_all_but(me)]
    )

    companions = FieldList(FormField(CompanionForm), min_entries=0)
    settlements = FieldList(FormField(SettlementForm), min_entries=1)

    description = TextAreaField(label="Description", validators=[Optional(strip_whitespace=True)])

    add = SubmitField(label="Add")

rembish_org/blueprints/trips.py
from flask import Blueprint, request, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.datastructures import MultiDict

from ..forms.trip import TripForm
from ..libraries.database import db
from ..libraries.templating import with_template
from ..models.trip import Trip, TripCompanion, TripSettlement
from ..models.user import User
from ..models.world import Settlement

root = Blueprint("trips", __name__)


@root.route("/trips")
@with_template
def map_():
    return {}


@root.route("/trips/list")
@with_template
def index():
    return {}


@root.route("/trips/add", methods=("GET", "POST"))
@login_required
@with_template
def add():
    data = None

    if request.method == "POST":
        companions = request.form.getlist("companion_ids").copy()
        data = MultiDict()
        i = 0
        for key, value in request.form.items(multi=True):
            if key.startswith("companions-"):
                user_id = key.lstrip("companions-")
                data[f"companions-{i}-user_id"] = user_id
                data[f"companions-{i}-full"] = value
                i += 1
                companions.remove(user_id)
            else:
                data.add(key, value)

        for user_id in companions:
            data[f"companions-{i}-user_id"] = user_id
            i += 1

    form = TripForm(formdata=data)
    if form.validate_on_submit():
        with db.session.no_autoflush:
            trip = Trip(traveler=current_user)
            for row in form.companions:
                tc = TripCompanion(companion=User.get_by(row.data["user_id"]))
                trip.companions.append(tc)
            for row in form.settlements:
                ts = TripSettlement(settlement=Settlement.get_or_create(**row.data["json"]))
                trip.settlements.append(ts)
            form.populate_obj(trip)
            db.session.add(trip)

        db.session.commit()
        return redirect(url_for("trips.index"))

    print(form.errors)

    return {
        "form": form,
    }

rembish_org/templates/trips/add.html
{% extends "layout.html" %}

{% block title %}Add a new trip - Alex Rembish{% endblock %}

{% block css %}
    <link href="{{ static_url('vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" rel="stylesheet">
    <link href="{{ static_url('vendor/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet">
    <style>
        #companions label {
            margin-left: 5px;
        }
    </style>
{% endblock %}

{% block js %}
    <script src="{{ static_url('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ static_url('vendor/bootstrap-select/js/bootstrap-select.min.js') }}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config['GOOGLE_API_KEY'] }}&libraries=places&language=en&callback=initMap"></script>

    <script>
        function initMap() {
            const map = new google.maps.Map(document.getElementById("map"), {
                center: {lat: 50.08804, lng: 14.42076},  // Default position is Prague
                zoom: 13,
                mapTypeId: "roadmap",
            });

            const locationInput = document.getElementById("location");
            const location = $(locationInput);
            const searchBox = new google.maps.places.SearchBox(locationInput);

            let lastMarker = null, markers = [];

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition((position => {
                    const latitude  = position.coords.latitude;
                    const longitude = position.coords.longitude;
                    map.setCenter(new google.maps.LatLng(latitude, longitude));
                }));
            }

            map.addListener("bounds_changed", () => {
                searchBox.setBounds(map.getBounds());
            });

            searchBox.addListener("places_changed", () => {
                const places = searchBox.getPlaces();
                if (places.length === 0 || !places[0].geometry) {
                    return;
                }
                location.removeClass("is-invalid");

                const place = places[0];
                if (!place.types.includes("locality")) {
                    location.addClass("is-invalid");
                    return;
                }

                let iso = null;
                for (const component of place.address_components) {
                    if (component.types.includes("country")) {
                        iso = component.short_name;
                    }
                }

                const data = {
                    name: place.name,
                    country_code: iso,
                    location: [place.geometry.location.lat(), place.geometry.location.lng()],
                    place_id: place.place_id
                }

                const index = parseInt(location.data("index"));
                $("#json").val(JSON.stringify(data));

                const bounds = new google.maps.LatLngBounds();
                const icon = {
                    url: place.icon,
                    size: new google.maps.Size(71, 71),
                    origin: new google.maps.Point(0, 0),
                    anchor: new google.maps.Point(17, 34),
                    scaledSize: new google.maps.Size(25, 25),
                };
                const placeLocation = place.geometry.location;

                lastMarker = new google.maps.Marker({
                  map, icon,
                  title: place.name,
                  position: placeLocation,
                });

                if (place.geometry.viewport) {
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }

                map.fitBounds(bounds)
            });
        }

        $(document).ready(() => {
            $(".btn-group-toggle input").change((e) => {
                $(e.currentTarget).parent().toggleClass("btn-secondary").toggleClass("btn-primary");
            });

            $("#companion_ids").on('changed.bs.select', (e, clickedIndex, isSelected, previousValue) => {
                const selected = $("option:eq(" + clickedIndex + ")", $("#companion_ids"));
                console.log(selected.html());
                const index = selected.val();
                const ns = selected.html().split(" ").map((n) => n[0]).join("");

                if (isSelected) {
                    let label = $("#companions>label:first").clone(true, true);
                    $("input:eq(0)", label).prop("id", "companions-" + index).prop("name", "companions-" + index);
                    $("span:eq(0)", label).html(ns);
                    label.removeClass("d-none");
                    $(label).insertAfter("#companions>label:last");
                } else {
                    $("#companions-" + index).parent().remove();
                }
            });

            $(".settlement-delete").click(function() {
                $(this).closest(".form-row").remove();
                return false;
            });

            $("#settlement-add").click(() => {
                let location = $("#location");
                let button = $("#settlement-add");
                button.prop('disabled', true);

                let index = parseInt(location.data("index"));
                const json = $("#json");

                if (location.hasClass("is-invalid") || !json.val()) {
                    button.prop('disabled', false);
                    return false;
                }

                let row = $(this).closest(".form-row");
                let div = $("#settlements>div:first").clone(true, true);
                $("input", div).each((i, element) => {
                    const old_id = $(element).prop("id").replace("--", "-" + index + "-");
                    const new_id = $(element).prop("id").replace("--", "-" + (index + 1) + "-");

                    const old = $("input[name='" + old_id + "']");
                    const value = old.val();
                    old.prop("name", new_id);

                    $(element).prop("id", old_id).prop("name", old_id).val(value);

                    if (old.prop("checked")) {
                        $(element).prop("checked", old.prop("checked"));
                    }
                });
                div.removeClass("d-none");
                $(div).insertBefore("#settlements>div:last");

                index++;
                location.val("").removeClass("is-invalid").data("index", index);
                json.val("");
                $("#slightly").prop("checked", false);
                button.prop("disabled", false);

                return false;
            });
        });
    </script>
{% endblock %}

{% block main %}
    <section>
        <div class="container">
            <div class="section-title">
                <h2>Add a new trip</h2>
            </div>

            <form method="post" action="{{ url_for('trips.add') }}">
                {{ form.csrf_token }}
                <div class="form-row">
                    <div class="form-group col-2">
                        <div class="input-group date" data-provide="datepicker" data-date-format="dd.mm.yyyy" data-date-week-start="1">
                            {{ form.start_date(class_="form-control", placeholder="From") }}
                            <div class="input-group-append">
                                <div class="input-group-text"><span class="icofont icofont-calendar"></span></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-2">
                        <div class="input-group date" data-provide="datepicker" data-date-format="dd.mm.yyyy" data-date-week-start="1">
                            {{ form.finish_date(class_="form-control", placeholder="To") }}
                            <div class="input-group-append">
                                <div class="input-group-text"><span class="icofont icofont-calendar"></span></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-3">{{ form.type(class_="form-control selectpicker") }}</div>
                </div>
                <div class="form-row">
                    <div class="form-group col-4">
                        {{ form.companion_ids(class_="form-control selectpicker", data_none_selected_text="Companions", data_selected_text_format="static", data_live_search="true") }}
                    </div>
                    <div class="form-group col">
                        <div class="btn-group-toggle" data-toggle="buttons" id="companions">
                          <label class="btn btn-primary active d-none">
                            <input type="checkbox" checked autocomplete="off"> <span></span>
                          </label>
                        {% for sub in form.companions %}
                          <label class="btn btn-{{ "primary active" if sub.full.data else "secondary" }}">
                            <input type="checkbox" autocomplete="off"{{ " checked" if sub.full.data }} name="companions-{{ sub.user_id.data }}" id="companions-{{ sub.user_id.data }}">
                            <span>{{ sub.user.initials }}</span>
                          </label>
                        {% endfor %}
                        </div>
                    </div>
                </div>

                <div id="map" style="height: 300px; margin-bottom: 10px;"></div>

                <div class="form-row">
                    <div class="form-group col-2">Date</div>
                    <div class="form-group col">Settlement</div>
                    <div class="form-group col-1">Slightly?</div>
                    <div class="form-group col-1">&nbsp;</div>
                </div>

                <div id="settlements">
                    <div class="form-row d-none">
                        <div class="form-group col-2">
                            <div class="input-group date" data-provide="datepicker" data-date-format="dd.mm.yyyy" data-date-week-start="1" data-date-clear-btn="true">
                                <input class="form-control" id="settlements--date" placeholder="Optional" type="text" value="">
                                <div class="input-group-append"><div class="input-group-text"><span class="icofont icofont-calendar"></span></div></div>
                            </div>
                        </div>
                        <div class="form-group col">
                            <input class="form-control" id="settlements--location" readonly type="text" value="">
                            <input id="settlements--json" type="hidden" value="">
                        </div>
                        <div class="form-group col-1"><input class="form-control" id="settlements--slightly" type="checkbox" value="y"></div>
                        <div class="form-group col-1"><button class="btn btn-outline-danger settlement-delete"><span class="icofont icofont-trash"></span></button></div>
                    </div>
                {% for row in form.settlements %}
                    <div class="form-row">
                        <div class="form-group col-2">
                            <div class="input-group date" data-provide="datepicker" data-date-format="dd.mm.yyyy" data-date-week-start="1" data-date-clear-btn="true">
                                {{ row.date(class_="form-control", placeholder="Optional") }}
                                <div class="input-group-append"><div class="input-group-text"><span class="icofont icofont-calendar"></span></div></div>
                            </div>
                        </div>
                        <div class="form-group col">
                            {{ row.location(class_="form-control", placeholder=row.location.label.name, id="location" if loop.last, data_index=loop.index0, readonly=not loop.last) }}
                            <div class="invalid-feedback">Not a settlement</div>
                            {{ row.json(id="json" if loop.last) }}
                        </div>
                        <div class="form-group col-1">{{ row.slightly(class_="form-control", id="slightly" if loop.last) }}</div>
                        <div class="form-group col-1">
                            {% if loop.last %}
                            <button class="btn btn-outline-dark" id="settlement-add"><span class="icofont icofont-plus"></span></button>
                            {% else %}
                            <button class="btn btn-outline-danger settlement-delete"><span class="icofont icofont-trash"></span></button>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                </div>
                <div class="form-row"><div class="form-group col">{{ form.description(class_="form-control", placeholder=form.description.label.text) }}</div></div>

                {{ form.add(class_="form-control") }}
            </form>
        </div>
    </section>
{% endblock %}

rembish_org/templates/trips/index.html
{% extends "layout.html" %}

{% block title %}Trips index - Alex Rembish{% endblock %}

{% block main %}
    <section class="trips">
        <div class="container">
            <div class="section-title">
                <h2>Trips index</h2>
            </div>

            {% if current_user.has_role("administrator") %}
                <p class="text-right"><a href="{{ url_for("trips.add") }}" class="btn btn-primary btn-lg" role="button">Add a new trip</a></p>
            {% endif %}

            <div class="table-responsive"><table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Dates</th>
                        <th scope="col">Companions</th>
                        <th scope="col">Countries</th>
                        <th scope="col">Settlements</th>
                        <th scope="col">Type</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table></div>
        </div>
    </section>
{% endblock %}

rembish_org/templates/trips/map.html
{% extends "layout.html" %}

{% block title %}Travel map - Alex Rembish{% endblock %}

{% block js %}
    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config['GOOGLE_API_KEY'] }}&libraries=places&language=en&callback=initMap"></script>
    <script>
    function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
            center: {lat: 50.08804, lng: 14.42076},  // Default position is Prague
            zoom: 13,
            mapTypeId: "roadmap",
        });
    }
    </script>
{% endblock %}

{% block main %}
    <section class="travelmap">
        <div class="container">
            <div class="section-title">
                <h2>Travel map</h2>
            </div>

            <div class="row">
                <div class="col-4">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{{ url_for("trips.index") }}">Total trips</a> <span class="badge badge-primary badge-pill">TBD</span>
                        </li>
                    </ul>
                </div>
            </div>

            <div id="map" style="height: 550px; margin-bottom: 10px;"></div>
        </div>
    </section>
{% endblock %}